smart_ad_server_plugin:
  smart_ad_server_network_id:
    client: true
    default: ''
    regex: '^[\d]*$'
  smart_ad_server_through_trust_level:
    client: true
    default: 2
    enum: 'TrustLevelSetting'
  smart_ad_server_site_id:
      client: true
      default: ''
      regex: '^[\d]*$'
  smart_ad_server_page_id:
      client: true
      default: ''
      regex: '^[\d]*$'
  smart_ad_server_mobile_site_id:
        client: true
        default: ''
        regex: '^[\d]*$'
  smart_ad_server_mobile_page_id:
      client: true
      default: ''
      regex: '^[\d]*$'
  smart_ad_server_refresh_timeout:
      client: true
      default: ''
      regex: '^[\d]*$'
  smart_ad_server_topic_list_top_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_mobile_topic_list_top_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_topic_above_post_stream_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_mobile_topic_above_post_stream_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_topic_above_suggested_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_mobile_topic_above_suggested_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_topic_above_footer_code:
      client: true
      default: ''
      max: 50
      regex: '^[\d]*$'
  smart_ad_server_mobile_topic_above_footer_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_post_bottom_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_mobile_post_bottom_code:
    client: true
    default: ''
    max: 50
    regex: '^[\d]*$'
  smart_ad_server_nth_post_code:
    client: true
    default: ''
    min: 1